/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kriptografi;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author rangga
 */
public class DinamisPolyalphabeticForm extends javax.swing.JFrame {
    private JLabel[] lblKeysEnc, lblKeysDec; //array of JLabels
    private JTextField[] inpKeysEnc, inpKeysDec; //array of JTextFields
    private int count;
    private int empty_count = 0;
    
    /**
     * Creates new form DinamisPolyalphabetic
     */
    public DinamisPolyalphabeticForm(int count) {
        initComponents();
        setKeyField(count);
        this.count = count;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }
    
    public void setKeyField(int count){
        lblKeysEnc = new JLabel[11];
        inpKeysEnc = new JTextField[11];
        lblKeysDec = new JLabel[11];
        inpKeysDec = new JTextField[11];
        
        for(int i = 1; i <= count; i++){
            lblKeysEnc[i] = new JLabel();
            lblKeysEnc[i].setText("Kunci "+i);
            
            lblKeysDec[i] = new JLabel();
            lblKeysDec[i].setText("Kunci "+i);
            
            inpKeysEnc[i] = new JTextField(10);
            inpKeysDec[i] = new JTextField(10);
            
            panelEnc.setLayout(new GridLayout(0,2, -40, 10));
            panelEnc.add(lblKeysEnc[i]);
            panelEnc.add(inpKeysEnc[i]);
            panelEnc.revalidate();
            panelEnc.repaint();
            
            panelDec.setLayout(new GridLayout(0,2, -40, 10));
            panelDec.add(lblKeysDec[i]);
            panelDec.add(inpKeysDec[i]);
            panelDec.revalidate();
            panelDec.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        inpPlainText = new javax.swing.JTextField();
        lblPlainText = new javax.swing.JLabel();
        panelEnc = new javax.swing.JPanel();
        hr = new javax.swing.JPanel();
        inpCipherText = new javax.swing.JTextField();
        lblCipherText = new javax.swing.JLabel();
        btnEncrypt = new javax.swing.JButton();
        lblCipherText1 = new javax.swing.JLabel();
        inpCipherText1 = new javax.swing.JTextField();
        title1 = new javax.swing.JLabel();
        panelDec = new javax.swing.JPanel();
        btnDecrypt = new javax.swing.JButton();
        inpPlainText1 = new javax.swing.JTextField();
        lblPlainText1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPlainText.setText("PlainTeks");

        javax.swing.GroupLayout panelEncLayout = new javax.swing.GroupLayout(panelEnc);
        panelEnc.setLayout(panelEncLayout);
        panelEncLayout.setHorizontalGroup(
            panelEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        panelEncLayout.setVerticalGroup(
            panelEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        hr.setBackground(new java.awt.Color(204, 204, 204));
        hr.setPreferredSize(new java.awt.Dimension(617, 2));

        javax.swing.GroupLayout hrLayout = new javax.swing.GroupLayout(hr);
        hr.setLayout(hrLayout);
        hrLayout.setHorizontalGroup(
            hrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hrLayout.setVerticalGroup(
            hrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        lblCipherText.setText("CipherTeks");

        btnEncrypt.setText("Proses");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        lblCipherText1.setText("CipherTeks");

        title1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Dekripsi Teknik Polyalphabetical");

        javax.swing.GroupLayout panelDecLayout = new javax.swing.GroupLayout(panelDec);
        panelDec.setLayout(panelDecLayout);
        panelDecLayout.setHorizontalGroup(
            panelDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        panelDecLayout.setVerticalGroup(
            panelDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        btnDecrypt.setText("Proses");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        lblPlainText1.setText("PlainTeks");

        title2.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Enkripsi Teknik Polyalphabetical");

        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(hr, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblPlainText)
                                        .addGap(28, 28, 28)
                                        .addComponent(inpPlainText))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblCipherText)
                                        .addGap(18, 18, 18)
                                        .addComponent(inpCipherText)))
                                .addGap(113, 113, 113))
                            .addComponent(panelEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblPlainText1)
                                        .addGap(29, 29, 29)
                                        .addComponent(inpPlainText1))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblCipherText1)
                                        .addGap(18, 18, 18)
                                        .addComponent(inpCipherText1)))
                                .addGap(113, 113, 113))
                            .addComponent(panelDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGap(310, 310, 310))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(14, 14, 14)
                .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpPlainText)
                    .addComponent(lblPlainText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpCipherText)
                    .addComponent(lblCipherText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpCipherText1)
                    .addComponent(lblCipherText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpPlainText1)
                    .addComponent(lblPlainText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(469, 469, 469))
        );

        jScrollPane1.setViewportView(mainPanel);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        // TODO add your handling code here:
        if(inpPlainText.getText().length()==0){
            JOptionPane.showMessageDialog(null, 
                    "PlainTeks tidak boleh kosong.",
                    "PlainTeks Kosong!!", JOptionPane.ERROR_MESSAGE);
        }else{
            for(int i=1;i<=count;i++){
                if(inpKeysEnc[count].getText().length()==0)  
                    empty_count++;                
            }
            
            if(empty_count > 0){
                JOptionPane.showMessageDialog(null, 
                        "Mohon isi semua kunci.",
                        "Kunci Kosong!!", JOptionPane.ERROR_MESSAGE); 
                empty_count = 0;
            }
            else{
                ArrayList<String> keys = new ArrayList<>();
                for(int i = 1; i <= count; i++){
                    // set kunci
                    keys.add(inpKeysEnc[i].getText());
                    
                    // set field kunci di field dekripsi
                    inpKeysDec[i].setText(inpKeysEnc[i].getText());
                }
                
                PolyalphabeticCipher poly = new PolyalphabeticCipher(keys);
                String cipherText = poly.encrypt(inpPlainText.getText());
                
                // set cipher text field dekripsi
                inpCipherText.setText(cipherText);
                inpCipherText1.setText(cipherText);
            }
        }
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        // TODO add your handling code here:
        if(inpCipherText1.getText().length()==0){
            JOptionPane.showMessageDialog(null, 
                    "CiphetTeks tidak boleh kosong.",
                    "CiphetTeks Kosong!!", JOptionPane.ERROR_MESSAGE);
        }else{
            for(int i=1;i<=count;i++){
                if(inpKeysDec[count].getText().length()==0)  
                    empty_count++;                
            }
            
            if(empty_count > 0){
                JOptionPane.showMessageDialog(null, 
                        "Mohon isi semua kunci.",
                        "Kunci Kosong!!", JOptionPane.ERROR_MESSAGE); 
                empty_count = 0;
            }
            else{
                ArrayList<String> keys = new ArrayList<>();
                for(int i = 1; i <= count; i++){
                    // set kunci
                    keys.add(inpKeysDec[i].getText());
                    
                    // set field kunci di field enkripsi
                    inpKeysEnc[i].setText(inpKeysDec[i].getText());
                }
                
                PolyalphabeticCipher poly = new PolyalphabeticCipher(keys);
                String plainText = poly.decrypt(inpCipherText1.getText());
                
                // set cipher text field enkripsi
                inpPlainText.setText(plainText);
                inpPlainText1.setText(plainText);
            }
        }
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SelectCountForm().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DinamisPolyalphabeticForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DinamisPolyalphabeticForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DinamisPolyalphabeticForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DinamisPolyalphabeticForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DinamisPolyalphabeticForm(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JPanel hr;
    private javax.swing.JTextField inpCipherText;
    private javax.swing.JTextField inpCipherText1;
    private javax.swing.JTextField inpPlainText;
    private javax.swing.JTextField inpPlainText1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCipherText;
    private javax.swing.JLabel lblCipherText1;
    private javax.swing.JLabel lblPlainText;
    private javax.swing.JLabel lblPlainText1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelDec;
    private javax.swing.JPanel panelEnc;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
